export {default as Login} from './Auth/Login'
export{default as AdminDashboard} from './Admin/AdminDashboard'
export{default as DoctorDashboard} from './Doctor/DoctorDashboard'
export {default as ReceptionDashboard} from './Reception/ReceptionDashboard'
export{default as Patients} from './Reception/Patients'
export {default as RegisterPatient} from './Reception/RegisterPatient'
export {default as AppointmentForm} from './Reception/AppointmentForm'
export {default as Appointments} from './Reception/Appointments'
export {default as PatientDetail} from './Reception/PatientDetail'